### ISSUE TITLE
iterm.app is often iterm 2.app in /Applications/

### ISSUE THREAD

**Issue by snide** [stuartcryan/custom-iterm-applescripts-for-alfred#23]
Thanks for this fantastic little script. Just a note that when I donwloaded the latest version of "iTerm3" (aka... 2.9) it defaults to "iTerm 2.app" and calls the app "iTerm 2". Your script points to "iTerm.app" and "iTerm". Easy fix when I noticed the problem, but didn't know if I should submit a PR to fix or if this was something unique to my desktop.

Again, thanks for the work. Really nice to have this.

**Comment by cantonic** [comment]
In my case I had iTerm.app in `/Users/myusername/Applications/`. Mentioning the possibility of different paths in the README would be useful i think.

**Comment by snide** [comment]
He mentions it in the copy/paste script itself at the top which was helpful, I was just wondering if it should point to the actual defaults, which seems to be "iTerm 2"?

**Comment by stuartcryan** [comment]
I actually had this as well, it turns out that it doesn't default to iTerm 2... however what I have found that is if you already had iTerm.app in your downloads folder, downloaded a new copy and extracted it... OSX will automatically name it iTerm 2.app

This one has caught me several times. If you download the latest iTerm and extract into a new folder you should get it extracting as iTerm.app not iTerm 2.app. Can you please confirm?
Cheers,
Stuart
